[build]
publish = "."

[[redirects]]
  from = "/home"
  to = "/game "
  status = 200
 

  [[redirects]]
  from = "/home"
  to = "/about"
  status = 200
 

[[redirects]]
  from = "/home"
  to = "/blog"
  status = 200


  [[redirects]]
  from = "/home"
  to = "/partners "
  status = 200


  [[redirects]]
  from = "/home"
  to = "/home"
  status = 200
 

